### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by bitnom** [llealgt/DNC#1]
Great work you're doing. Was skimming through some of your DNC and ran into this

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]) tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-24-3b1912efe089> in <module>()
      4 
      5 # train the model
----> 6 train(net, encoded, epochs=n_epochs, batch_size=batch_size, seq_length=seq_length, lr=0.0015, val_frac=0.15 ,print_every=10)

<ipython-input-18-d5bd13ec1270> in train(net, data, epochs, batch_size, seq_length, lr, clip, val_frac, print_every, load_checkpoint)
     58             # get the output from the model
     59             #output, h = net(inputs, h)
---> 60             y_pred = net(inputs)
     61 
     62             # calculate the loss and perform backprop

~/anaconda2/envs/pytorch_challenge/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

<ipython-input-22-ad687f7874e6> in forward(self, x)
     52 
     53 
---> 54         read_content_weighting = self.content_lookup(self.memory_matrix,self.read_keys,self.read_strenghts)
     55         read_weighting = read_content_weighting
     56 

<ipython-input-22-ad687f7874e6> in content_lookup(self, matrix, keys, strengths)
     77         # calc cosine similarity between keys and memory locations
     78         print(matrix,matrix.t())
---> 79         cosine_similarity = torch.matmul(keys,matrix.t())/(keys_norm*matrix_norm)
     80 
     81         # do a "strenght" softmax to calculate the probability distribution

RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.FloatTensor for argument #2 'mat2'

**Comment by llealgt** [comment]
hello, yes, this is something i'm working on right now(it's work in progress and still  in very early stage) , this is something i expect to work on to fix, what is happening is that for some reason the memory matrix is on CPU and the rest of the model and tensors are in GPU , i still have to find why and how to fix it

**Comment by llealgt** [comment]
https://stackoverflow.com/questions/54155969/pytorch-instance-tensor-not-moved-to-gpu-even-with-explicit-cuda-call

**Comment by llealgt** [comment]
Fixed : https://github.com/llealgt/DNC/commit/b723081930929839af73ddd7b428a10021731b78
